version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule: { interval: weekly }
    groups:
      spring: { patterns: ["org.springframework*", "org.springframework.boot*", "org.springframework.cloud*"] }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
