apiVersion: v1
kind: Secret
metadata:
  name: commerce-databases
type: Opaque
stringData:
  username: commerce
  password: CHANGE_ME
  products-url: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/products
  inventory-url: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/inventory
  orders-url: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/orders
  payments-url: jdbc:postgresql://postgresql.database.svc.cluster.local:5432/payments
