server.port: 8083
spring:
  application.name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/orders}
    username: ${DB_USER:commerce}
    password: ${DB_PASSWORD:commerce}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
  flyway.enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: dev.ilyas.commerce.events
        spring.json.value.default.type: dev.ilyas.commerce.events.CommerceEvents$PaymentCompleted
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener.ack-mode: record
clients.inventory.base-url: ${INVENTORY_URL:http://localhost:8082}
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.health.probes.enabled: true
  metrics.tags.application: ${spring.application.name}
