apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-commerce
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/therealilyas/cloud-commerce-platform.git
    targetRevision: main
    path: deploy/helm/cloud-commerce
  destination:
    server: https://kubernetes.default.svc
    namespace: commerce
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
