server.port: 8082
spring:
  application.name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/inventory}
    username: ${DB_USER:commerce}
    password: ${DB_PASSWORD:commerce}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
  flyway.enabled: true
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.health.probes.enabled: true
  metrics.tags.application: ${spring.application.name}
